# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yZs4ldbb080etxlAX8DjdDJttyQ8Kkid
"""

def imprimir_serie():
    print("Vamos começar a construir sua série.")
    nome = input("Digite seu nome: ")
    numero = int(input("Qual o número de exercícios você deseja fazer? "))
    nexercicios = 0
    while nexercicios < numero:
        nomeexercicio = input(f"Digite o nome da série {nexercicios+1}: ")
        print(f"Série {nexercicios+1} é {nomeexercicio}.")
        serie = int(input(f"Quantas séries do exercício {nomeexercicio} você quer fazer? "))
        quantidade = 0
        while quantidade < serie:
            print(f"{nomeexercicio} {quantidade+1}")
            quantidade += 1
        nexercicios += 1

print("Academia Perde Apança. Seja bem-vindo.")
imprimir = input("Vamos imprimir sua série de exercícios? Digite 'Sim' para imprimir, ou 'Não' para sair. ").lower()

while imprimir != "sim" and imprimir != "não":
    imprimir = input("Opção inválida. Digite 'Sim' para imprimir, ou 'Não' para sair. ").lower()

if imprimir == "sim":
    imprimir_serie()
elif imprimir == "não":
    print("Ok, bom treino. Qualquer dúvida, só chamar o professor.")
    
print("Bom treino. Academia Perde Apança agradece sua preferência.")